### ISSUE TITLE
Google Analytics export (may be an epic)

### ISSUE THREAD

**Issue by annepetersen** [18F/delivery-assurance#115]
Very possible that this may need to be broken down further to make it accomplishable in two weeks: we might consider doing this by 18F property (see Acceptance criteria, below).

### A description of the work
We need to export Google Analytics data since we will [need to move to GA4 at some point](https://docs.google.com/document/d/1PtzgTKDxfQnvt59IY7PoH45KLmDXBQr5lVC8Dr8WavA/edit#heading=h.7lp57d55pp5e) (either this July, or next July, depending on if we join the GSA instance before then).

### Point of contact on this issue
@annepetersen, @michelle-rago 

### Reproduction steps (if necessary)
[Instructions](https://docs.google.com/document/d/1PtzgTKDxfQnvt59IY7PoH45KLmDXBQr5lVC8Dr8WavA/edit#heading=h.c5c4fi6plvug)
- get access to our Google Analytics instance
- Select the property (for 18F, probably for each individual microproperty)
- on the “migrating” modal, select “skip for now”
- choose full URLs
- select the entirety of the time available for each
- export in PDF (for dashboard view)
- export in CSV (for data breakdown)
- consider particular views we may need: geography (including outside U.S.), browser, etc.

**Billable?**

- [ ] Yes
- [X] No

**Skills needed**

- [X] Any human
- [ ] Design
- [ ] Content
- [ ] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

**Timeline**
Does this need to happen in the next two weeks?

- [ ] Yes
- [X] No

How much time do you anticipate this work taking?
Unknown! Gray and Leigh are testing this soon to see how far they can get in an hour. Anne may have an update next Monday

### Acceptance Criteria

- [ ] Done looks like: An organized Google Drive folder contains both PDFs and CSVs for accurately exported analytics data for all relevant 18F properties. 

Priority order might be: 
- [ ] 18F main site
- [ ] 18F Accessibility Guide 
- [ ] Agile Guide
- [ ] Brand Guide
- [ ] Content Guide
- [ ] De-risking Guide
- [ ] Engineering Hiring Guide 
- [ ] Engineering Practices Guide 
- [ ] Methods
- [ ] Product Guide
- [ ] UX Guide
- [ ] any other 18F properties we may want to retain data on

**Comment by MelissaBraxton** [comment]
The scope of this may just be downloading GA 3 data and storing it for possible later use.
