### ISSUE TITLE
Set up onboarding and offboarding issue templates

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/delivery-assurance#117]
### A description of the work
This issue covers creating standardized GitHub issue templates to make sure we are consistent in how we onboard and off-board folks to the group and that nothing falls through the cracks. 

### Point of contact on this issue
@MelissaBraxton 

**Billable?**

- [ ] Yes
- [X] No
If yes, tock code:

**Skills needed**

- [X] Any human
- [ ] Design
- [ ] Content
- [ ] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

**Timeline**
Does this need to happen in the next two weeks?

- [X] Yes
- [ ] No

How much time do you anticipate this work taking?
1-2 hours

### Acceptance Criteria
- [x] As a new person joining the group, I can track my progress as I get up to speed and easily surface any blockers to my contributing. 
- [x] As a DA team lead, I can easily track the work of ensuring that each new group member has what they need to successfully contribute so that I can onboard folks consistently and efficiently and prevent things from falling through the cracks.
- [x] Onboarding and off boarding issue templates include checklist items for granting and revoking access to all needed repos, teams, and groups
- [x] Documentation of onboarding/offboarding process in GitHub wiki is up to date

### Tasks
 - [x] Review existing onboarding and off boarding checklists [here](https://github.com/18F/delivery-assurance/blob/main/docs/onboarding-offboarding-checklists.md)
 - [x] Create an onboarding issue template in GitHub
 - [x] Create an off-boarding issue template in GitHub
 - [x] Update content [here](https://github.com/18F/delivery-assurance/blob/main/docs/onboarding-offboarding-checklists.md)
 - [x] PO reviews / approves PRs

**Comment by MelissaBraxton** [comment]
Boldly assigning myself, since I think this'll take less than 2 hrs.

**Comment by MelissaBraxton** [comment]
Heads up this one is still waiting on a review of [this PR ](https://github.com/18F/delivery-assurance/pull/126)from @alexbielen and/or @kfoley-18F

**Comment by alexbielen** [comment]
@MelissaBraxton I reviewed #126 and left a few comments!

**Comment by MelissaBraxton** [comment]
Done pending review/merge on updates to the wiki in [PR 137](https://github.com/18F/delivery-assurance/pull/137)
