### ISSUE TITLE
Create sustainable increment cadence

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/delivery-assurance#141]
### A description of the work
This issue covers establishing a cadence for planning increments, onboarding new folks, retros, etc. that is sustainable for team leads and team members.

**Billable?**

- [ ] Yes
- [ X] No
If yes, tock code:

**Skills needed**

- [x] Any human
- [ ] Design
- [ ] Content
- [ ] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

**Timeline**
Does this need to happen in the next two weeks?

- [ X] Yes
- [ ] No

How much time do you anticipate this work taking?
1 day or two depending on time it takes to get consensus

### Acceptance Criteria

- [ ] Cadence allows us to plan increment goals matched to skills and capacity on the team
- [ ] Cadence gives team leads time to learn about incoming team members' skilss/capacity prior to planning an increment
- [ ] We've adjusted calendar events accordingly
- [ ] We've communicated anything we need from to staffing and gotten their concurrence
 
### Tasks
 - [x] Alex and Melissa draft a proposed cadence
 - [x] Alex, Melissa, and Kelsey review/discuss/refine
 - [x] Draft proposal re: cadence changes for staffing office hours
 - [x] Get concurrence on any changes that involve staffing from staffing reps
 - [x] Adjust calendar events as needed

**Comment by MelissaBraxton** [comment]
Hey there, @kfoley-18F  - Alex and I are proposing some changes to the cadence [here. ](https://docs.google.com/document/d/1BM5piLtRg0q40kN7SIBZ5aNjKKBnz4H1uaN28jeLFZY/edit#). If you could take a look and provide feedback when you have a sec, that'd be awesome!

**Comment by MelissaBraxton** [comment]
Proposal re: cadence change that impacts staffing is with staffing crew for reps for review. Will run through alignment process with them tomorrow, 4/20.
