### ISSUE TITLE
Set up automation to make it easy to spot new issues

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/delivery-assurance#144]
### A description of the work
This issue covers researching and implementing a way to automatically flag issues as new so that crew members can see what issues might need to be refined and prioritized. This item came out of a retro.

Possible approaches 
- A "new" column as the default place where new issues land
- A "new issue" label that is automatically applied to new issues. (cons: the label needs to be manually removed, and it may be tricky given that issues may be tied to different repos)

### Point of contact on this issue
@MelissaBraxton 

**Billable?**

- [ ] Yes
- [X] No
If yes, tock code:

**Skills needed**

- [ ] Any human
- [ ] Design
- [ ] Content
- [X] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

**Timeline**
Does this need to happen in the next two weeks?

- [X] Yes
- [ ] No

How much time do you anticipate this work taking?
2 hours

### Acceptance Criteria

- [ ] As someone on the DA crew, I can easily determine which issues are new and may need refinement and/or prioritization. 
- [ ] Whatever solution we come up with to flag new issues is automated 

### Tasks
- [ ] Research what kind of automation would make the most sense
- [ ] Lay out tradeoffs of different approaches for @alexbielen and @MelissaBraxton (could be as lightweight as a Slack message or a 15 min. chat to discuss)
- [ ] Create a PR to implement automation
- [ ] Tag @alexbielen as a reviewer

**Comment by julialeague** [comment]
So far, I've set up a column called "New" that is set to be the default landing column for newly-logged issues. This takes care of future issues, not existing ones.

We could also optionally use a GitHub Action to add a "new" label to issues logged from our related repos. See an example of the code update we'd make to do that here: https://github.com/18F/18f.gsa.gov/compare/jallen/tlc-144-new-issue-label?expand=1

It will take some more research to see if there's a way to auto-remove the "new" label when the issue is moved to a different Column/Status.

**Comment by julialeague** [comment]
The blocker for automating the removal of the “new” label when the Column is changed is that (AFAIC) there’s currently no way to trigger a workflow when an issue is moved to a new column on Projects v2. It’s probably one of those features that’s in the GitHub backlog right now, since Projects v2 is still pretty new. We could alternatively have a scheduled workflow that will scan for issues labeled “new” that aren’t in the “new” column, and remove the “new” label at that point. This may cause confusion and make filtering less useful. Also, luckily, we can already filter by Column in list views, so maybe a "new" label is redundant to the New column.

Thoughts? 

Tagging @MelissaBraxton and @alexbielen for thoughts and opinions. Thanks!
