### ISSUE TITLE
Update 18F tabs in TTS Onboarding Checklist

### ISSUE THREAD

**Issue by juliaklindpaintner** [18F/delivery-assurance#173]
### A description of the work
The current 18F tabs in the [TTS Onboarding Checklist](https://docs.google.com/spreadsheets/u/0/d/1w0WSTUT0l7q19mAI6c2QCIpCFs0Cei4eukaiiRBTbRA/edit) document are out of date and there is no standard process for reviewing these regularly.

Tasks:

- [ ] Review 18F tabs for accuracy (up-to-date, links work, etc)
- [ ] Consider additional improvements that would make the instructions clearer or easier to act on
- [ ] Consider the pros/cons of creating a consolidated “18F” tab with the items that appear on all the chapter lists, so that the chapter lists are chapter-specific activities
- [ ] Propose a solution for ownership and ongoing maintenance of these checklists going forward

### Point of contact on this issue
@juliaklindpaintner as issue author
@AnnabelLombard and @hilarylutz are TTS Onboarding contacts. They can grant edit access to the checklist, but it may be easiest to work in a copy and then have them implement changes when all is confirmed.

**Billable?**

- [ ] Yes
- [x] No
If yes, tock code:

**Skills needed**

I think anyone could work on this, but noting that some consideration of user experience and content design are implied.
- [x] Any human
- [ ] Design
- [ ] Content
- [ ] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

**Timeline**
Does this need to happen in the next two weeks?

- [ ] Yes
- [x] No

How much time do you anticipate this work taking?
Depends: Will require some collaboration with each chapter to verify what is/is not up to date. 

### Acceptance Criteria

- [ ] 18F tabs do not contain broken links or out-of-date information
- [ ] As a new 18F employee, I understand what I need to do to complete the items on my checklist
- [ ] Updated content has been incorporated into the TTS Onboarding Checklist

**Comment by juliaklindpaintner** [comment]
I'd be more than happy to have a conversation about this issue if useful. I can note a few things that I've already observed to be out of date and talk about the consideration around putting all the 18F general items in one place and making the language clearer.

**Comment by donnykwan** [comment]
@juliaklindpaintner I am working on this.  Would like to grab a time to chat before you taking off.

**Comment by donnykwan** [comment]
I have check and updated the 18F tabs on [TTS onboarding checklist](https://docs.google.com/spreadsheets/d/1SVe_ky85FYe5Ag0eVKmuspWeyrzjFFAINGnwp6ZtbIY/edit#gid=1281322371), there are a couple of items that I am unable to get any answers.

Few recommendations:
1. Each chapter has its own version of checklist, and there are discrepancies between Chapters, for example, Acq chapter has 14 lines, and Account Manager chapter 28 lines.  It will be ideal for all the chapter leads to work on the checklists together, and identify some common list for all the new employees, and additionally, a list for each individual chapter.
2. Try not to use individual names, fixed date time for meetings in the checklist  as folks at 18F change move or change responsibilities often. 
3. Many of the doc the list pointed to have outdated info, @MelissaBraxton has created a new tickets to update those docs. 
4. Identify a owner (s) for checking and updating the checklist quarterly or bi-annually.

**Comment by MelissaBraxton** [comment]
@donnykwan  - Requested access! in reviewing this ticket, it sounds like your recommendation re: a tab for **all of 18F** and then separate tabs for chapter-specific checklists matches Julia's initial recommendation. 

1. A next step for you here is to follow through on that recommendation by pulling list items that are repeated on all checklists into their own **all of 18F** tab. 
2. Another task in the initial ask is to propose a solution to address the need for ongoing ownership. Item 4 in your note above reiterates this need, but can you take it a step further and suggest who might own this? 
3. Last, I think we can meet the acceptance criteria for ensuring that the revised checklist is understandable to a new person by recruiting someone who joined 18F in the last 3 months to review the checklists and provide and address their feedback. 

After you've completed these tasks, I think we'll be ready to share with the TTS Onboarding contacts to update.

**Comment by donnykwan** [comment]
1. I added a "all of 18F tab" and crossed out the corresponding items in the Chapter tabs.  [red color tabs]
2. I proposed this to be owned by the "X of 18F Operation", with help from folks from all Chapters. 
3. TBD,

@alexbielen @MelissaBraxton

**Comment by donnykwan** [comment]
I will review this with @juliaklindpaintner,  the originator of the issue, next week when she will back from vacation.

@MelissaBraxton @alexbielen

**Comment by donnykwan** [comment]
@juliaklindpaintner I am scheduling a meeting this week to go over the updated [checklist](https://docs.google.com/spreadsheets/d/1SVe_ky85FYe5Ag0eVKmuspWeyrzjFFAINGnwp6ZtbIY/edit#gid=1281322371).

**Comment by MelissaBraxton** [comment]
@donnykwan  - Seems like this still belongs in "in review." Is that right? Any updates to share?

**Comment by donnykwan** [comment]
Got feedback from @allisonnorman (product) and @amymok (engineering), still waiting for @AshleyO85 (Acquisition) and @Erica-Perkins (Design) leads to response. 

The doc is [here](https://docs.google.com/spreadsheets/d/1SVe_ky85FYe5Ag0eVKmuspWeyrzjFFAINGnwp6ZtbIY/edit#gid=2123639024)
