### ISSUE TITLE
Check/fix alignment of case study page elements

### ISSUE THREAD

**Issue by egamble23** [18F/delivery-assurance#183]
Related to [issue #160](https://github.com/18F/delivery-assurance/issues/160) - this ticket focuses on the technical issue for screens wider than 1030px raised in that ticket. 

**A description of the work**
Fix section and aside alignment to match other page elements (this is an issue across [case study content](https://18f.gsa.gov/what-we-deliver/forest-service/)). This appears to affect mostly screens wider than 1030px

Example of alignment issue:
https://user-images.githubusercontent.com/2374206/232610937-5be3981f-931b-42e3-8f81-37a6fe650c4b.png

Point of contact on this issue
@cmajel 

**Billable?**

- [ ] Yes
- [X] No
If yes, tock code:

**Skills needed**

- [ ] Any human
- [X] Design
- [ ] Content
- [X] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

**Timeline**
Does this need to happen in the next two weeks?
- [ ] Yes
- [x] No

How much time do you anticipate this work taking?
Under 2 weeks

Acceptance Criteria
 - [ ] Apply appropriate fixes to alignment to match other page elements across [case study content](https://18f.gsa.gov/what-we-deliver/forest-service/)) so it displays well even for screens wider than 1030px

### Tasks
- [ ] Review alignment of elements on case study pages
- [ ] Develop appropriate solution 
- [ ] Implement
