### ISSUE TITLE
Develop a template for scoping and approving Epic-level DA initiatives

### ISSUE THREAD

**Issue by colinmurphy01** [18F/delivery-assurance#74]
### A description of the work
Just because the DA Team is operating on a 2-week cadence, doesn't mean they can't support long-term initiatives that go beyond 2 weeks or require coordination across multiple efforts. 

However in order for this work to be managed successfully, it needs to be proposed, scoped, agreed upon in writing in order to ensure alignment across DA Team cohorts.

### Point of contact on this issue
@colinmurphy01 @kfoley-18F 

**Billable?**

- [ ] Yes
- [x] No
If yes, tock code:

**Skills needed**

- [x] Any human
- [ ] Design
- [ ] Content
- [ ] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

**Timeline**
Does this need to happen in the next two weeks?

- [x] Yes
- [ ] No

How much time do you anticipate this work taking?
2 weeks 

### Acceptance Criteria

- [ ] There is a proposal template of required information in order for an Epic to be considered and prioritized for the DA Team
- [ ] There is a process for review of initiatives
- [ ] There is a running list of potential Epic-level initiatives to monitor

**Comment by colinmurphy01** [comment]
[Template](https://docs.google.com/document/d/1daGZGh18V8ZZPY0k3YNPpL5OJ7nBdI2FdKsEOwx83OI/edit#)

**Comment by colinmurphy01** [comment]
@kfoley-18F I'm going to co-assign you this ticket and label that this is blocked till LT figures out how they want to consolidate the process for epic proposals / asks for supes.

**Comment by kfoley-18F** [comment]
*I'm* okay with this Epics proposal, but I think running it by the new supes joining this space soon is probably good, as they will likely have feedback about it, given that they are present to help with continuity.

**Comment by alexbielen** [comment]
Notes from refinement: What counts as an Epic for us? How do we decide and communicate about it?

**Comment by alexbielen** [comment]
This is related to #152 so we should chat with @donnykwan about this as well
